#!/usr/bin/env bash

if [ ! -d $HOME/.config ]; then
  mkdir $HOME/.config;
fi

if [ ! -d $HOME/.config/dunst ]; then
  mkdir $HOME/.config/dunst;
fi

if [ ! -f $HOME/.config/dunst/dunstrc ]; then
  mv $PWD/config/dunstrc $HOME/.config/dunst/;
fi

if [ ! -d $HOME/.config/rofi ]; then
  mkdir $HOME/.config/rofi;
fi

if [ ! -f $HOME/.config/rofi/config.rasi ]; then
  mv $PWD/config/config.rasi $HOME/.config/rofi/;
fi

if [ ! -d $HOME/.config/mpv ]; then
  mkdir $HOME/.config/mpv;
fi

if [ ! -f $HOME/.config/mpv/mpv.conf ]; then
  echo 'fs=yes' > $HOME/.config/mpv/mpv.conf;
fi

if [ ! -d $HOME/.computer ]; then
  mv $PWD/.computer $HOME/;
fi

if [ ! -f $HOME/.xinitrc ]; then
  mv $PWD/.xinitrc $HOME/;
fi

git clone https://github.com/bakkeby/dwm-flexipatch.git

cd $PWD/dwm-flexipatch
mv $PWD/config/config.h $PWD/dwm-flexipatch
mv $PWD/config/patches.h $PWD/dwm-flexipatch
doas make clean install
cd ..

chmod +x $HOME/.computer/scripts/*

echo 'PATH=$PATH:$HOME/.computer/bin' >> $HOME/.bashrc
